print(70*'-')
print('     Class 02 \n     1. Kim \n     2. Chee')
print(70*'-')
print('     Cryptocurrency Portfolio Application Main Menu')
print(70*'-')
print('1. Display Cryptocurrency\n2. Add Cryptocurrency\n3. Amend Cryptocurrency\n4. Remove Cryptocurrency\n5. Crypto Portfolio Statement\n6. studentfunction1\n7. studentfunction2\nE. Exit Main Menu')
print(70*'-')
opt = input('Select and option: ')